name: CI Pipeline

on:  
  push:  
    branches:  
      - main

jobs:  
  format:  
    name: "Run Prettier Formatting"
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v3  

      - name: Setup Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '22'  

      - name: Install Dependencies  
        run: npm install  

      - name: Run Prettier  
        run: npm run format 

      - name: Custom Output  
        run: echo "Pipeline executada por Mateus"  
